data:extend(
{
  {
    type="item-subgroup",
    name="ore-machine",
    group="production",
    order="g"    
  },
  {
    type="item-subgroup",
    name="ore-separation",
    group="intermediate-products",
    order="h"    
  }  
})
