--require("prototypes.categories.recipe-category")
--require("prototypes.item.item")
--require("prototypes.entity.entity")
require("prototypes.fluid.fluid")
require("prototypes.technology.technology")
require("prototypes.recipe.chemfab-recipe")
--require("prototypes.recipe.boiler-recipe")
--require("prototypes.recipe.recipe")