data:extend(
{
  {
    type = "fluid",
    name = "hydrogen-gas",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=1, g=1, b=1},
    flow_color = {r=0.95, g=0.95, b=0.95},
    max_temperature = 100,
    icon = "__oil-resources-extended__/graphics/icons/fluid/hydrogen-gas.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "f[gas]-a[hydrogen-gas]"
  },
  {
    type = "fluid",
    name = "oxygen-gas",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.83, g=0.10, b=0.12},
    flow_color = {r=0.83, g=0.20, b=0.20},
    max_temperature = 100,
    icon = "__oil-resources-extended__/graphics/icons/fluid/oxygen-gas.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "f[gas]-b[oxygen-gas]"
  },
  {
    type = "fluid",
    name = "nitrogen-gas",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.05, g=0.75, b=0.91},
    flow_color = {r=0.15, g=0.80, b=0.95},
    max_temperature = 100,
    icon = "__oil-resources-extended__/graphics/icons/fluid/nitrogen-gas.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "f[gas]-c[nitrogen-gas]"
  },
  {
    type = "fluid",
    name = "coal-slurry",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.15, g=0.05, b=0},
    flow_color = {r=0.35, g=0.2, b=0.2},
    max_temperature = 100,
    icon = "__oil-resources-extended__/graphics/icons/fluid/coal-slurry.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "g[fuel]-a[coal-slurry]"
  },
  {
    type = "fluid",
    name = "quality-coal-slurry",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.15, g=0.05, b=0},
    flow_color = {r=0.35, g=0.2, b=0.2},
    max_temperature = 100,
    icon = "__oil-resources-extended__/graphics/icons/fluid/quality-coal-slurry.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "g[fuel]-b[quality-coal-slurry]"
  },
  {
    type = "fluid",
    name = "pyro-oil",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.15, g=0.05, b=0},
    flow_color = {r=0.35, g=0.2, b=0.2},
    max_temperature = 100,
    icon = "__oil-resources-extended__/graphics/icons/fluid/pyro-oil.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "g[fuel]-c[pyro-oil]"
  },
  {
    type = "fluid",
    name = "shale-oil",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.15, g=0.05, b=0},
    flow_color = {r=0.35, g=0.2, b=0.2},
    max_temperature = 100,
    icon = "__oil-resources-extended__/graphics/icons/fluid/shale-oil.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "g[fuel]-d[shale-oil]"
  },
  {
    type = "fluid",
    name = "fuel-oil",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.15, g=0.05, b=0},
    flow_color = {r=0.35, g=0.2, b=0.2},
    max_temperature = 100,
    icon = "__oil-resources-extended__/graphics/icons/fluid/fuel-oil.png",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    order = "g[fuel]-e[fuel-oil]"
  }  
})
